pipeline {
  agent any

  tools { nodejs 'node20' }

  triggers {
    pollSCM('* * * * *')
  }

  environment {
    GITHUB_CREDENTIALS = 'github-pat'
    GITHUB_USER = 'busra-ertekin'
    BUILD_REPO = "jenkins-builds"
    REPO_NAME = "jenkins-demo-project"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout([$class: 'GitSCM',
          branches: [[name: '*/main']],
          userRemoteConfigs: [[
            url: "https://github.com/${env.GITHUB_USER}/${env.REPO_NAME}.git",
            credentialsId: env.GITHUB_CREDENTIALS
          ]]
        ])
      }
    }

    stage('Install dependencies') {
      steps {
        sh '''
          echo "Current directory: $(pwd)"
          node -v
          npm ci
        '''
      }
    }

    stage('Bump version & tag') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: env.GITHUB_CREDENTIALS,
          usernameVariable: 'GIT_USER',
          passwordVariable: 'GIT_TOKEN'
        )]) {
          sh '''
            echo "Git status before bump:"
            git status

            git config user.email "jenkins@busra-ertekin.com"
            git config user.name "jenkins-ci"

            git remote set-url origin https://${GIT_TOKEN}@github.com/${GITHUB_USER}/${REPO_NAME}.git

            npm version patch -m "ci: bump version to %s [ci skip]"

            git push origin HEAD:main --follow-tags

            echo "Version bumped and pushed to GitHub"
          '''
        }
      }
    }

    stage('Build Application') {
      steps {
        sh '''
          echo "Building Next.js application..."
          npm run build
          echo "Build completed"
        '''
      }
    }

    stage('Docker build') {
      steps {
        sh '''
          IMAGE_TAG="${GITHUB_USER}/${REPO_NAME}:$(git rev-parse --short HEAD)"
          echo "Building Docker image: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .
          echo "Docker image built: $IMAGE_TAG"
        '''
      }
    }

    stage('Create and Push Artifact') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: env.GITHUB_CREDENTIALS,
          usernameVariable: 'GIT_USER',
          passwordVariable: 'GIT_TOKEN'
        )]) {
          sh '''
            set -e

            BUILD_DATE=$(date +"%Y%m%d-%H%M%S")
            COMMIT_SHA=$(git rev-parse --short HEAD)
            VERSION=$(node -p "require('./package.json').version")

            ARTIFACT_NAME="artifact-v${VERSION}-${BUILD_DATE}-${COMMIT_SHA}.tar.gz"

            echo "================================================"
            echo "Creating FULL artifact: ${ARTIFACT_NAME}"
            echo "Version: v${VERSION}"
            echo "Date: ${BUILD_DATE}"
            echo "Commit: ${COMMIT_SHA}"
            echo "================================================"

            # Tüm proje dosyalarını dahil et (.git hariç)
            tar --exclude='.git' --exclude='node_modules' -czf ${ARTIFACT_NAME} *

            echo "Artifact created: $(ls -lh ${ARTIFACT_NAME})"

            TMPDIR=$(mktemp -d)
            echo "Cloning jenkins-builds repository..."
            git clone https://${GIT_TOKEN}@github.com/${GITHUB_USER}/${BUILD_REPO}.git $TMPDIR

            cp ${ARTIFACT_NAME} $TMPDIR/

            cd $TMPDIR

            git config user.email "jenkins@busra-ertekin.com"
            git config user.name "jenkins-ci"

            git add ${ARTIFACT_NAME}

            COMMIT_MSG="Add full build artifact ${ARTIFACT_NAME}

Project: ${REPO_NAME}
Version: v${VERSION}
Build Date: ${BUILD_DATE}
Commit: ${COMMIT_SHA}
Build Number: ${BUILD_NUMBER}

Generated by Jenkins CI/CD Pipeline"

            git commit -m "${COMMIT_MSG}" || true
            echo "Pushing to GitHub..."
            git push origin HEAD:main

            cd -
            rm -rf $TMPDIR

            echo "================================================"
            echo "SUCCESS! Full artifact pushed to GitHub"
            echo "Repository: https://github.com/${GITHUB_USER}/${BUILD_REPO}"
            echo "File: ${ARTIFACT_NAME}"
            echo "================================================"
          '''
        }
      }
    }

    stage('Build Summary') {
      steps {
        sh '''
          BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S")
          COMMIT_SHA=$(git rev-parse --short HEAD)
          VERSION=$(node -p "require('./package.json').version")

          echo "========================================"
          echo "BUILD SUMMARY"
          echo "========================================"
          echo ""
          echo "Project:        ${REPO_NAME}"
          echo "Version:        v${VERSION}"
          echo "Build Date:     ${BUILD_DATE}"
          echo "Commit:         ${COMMIT_SHA}"
          echo "Build Number:   ${BUILD_NUMBER}"
          echo ""
          echo "Repositories:"
          echo "  Source:  https://github.com/${GITHUB_USER}/${REPO_NAME}"
          echo "  Builds:  https://github.com/${GITHUB_USER}/${BUILD_REPO}"
          echo ""
          echo "All stages completed successfully!"
          echo ""
        '''
      }
    }
  }

  post {
    success {
      echo 'PIPELINE COMPLETED SUCCESSFULLY!'
    }
    failure {
      echo 'PIPELINE FAILED!'
    }
    always {
      cleanWs()
    }
  }
}
pipeline {
  agent any
  
  tools { nodejs 'node20' }
  
  triggers {
    pollSCM('* * * * *')
  }
  
  environment {
    GITHUB_CREDENTIALS = 'github-pat'
    GITHUB_USER = 'busra-ertekin'
    BUILD_REPO = "jenkins-builds"
    REPO_NAME = "jenkins-demo-project"
  }
  
  stages {
    stage('Checkout') {
      steps {
        checkout([$class: 'GitSCM',
          branches: [[name: '*/main']],
          userRemoteConfigs: [[
            url: "https://github.com/${env.GITHUB_USER}/${env.REPO_NAME}.git",
            credentialsId: env.GITHUB_CREDENTIALS
          ]]
        ])
      }
    }
    
    stage('Install dependencies') {
      steps {
        sh '''
          echo "Current directory: $(pwd)"
          node -v
          npm ci
        '''
      }
    }
    
    stage('Bump version & tag') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: env.GITHUB_CREDENTIALS,
          usernameVariable: 'GIT_USER',
          passwordVariable: 'GIT_TOKEN'
        )]) {
          sh '''
            echo "Git status before bump:"
            git status
            
            git config user.email "jenkins@busra-ertekin.com"
            git config user.name "jenkins-ci"
            
            git remote set-url origin https://${GIT_TOKEN}@github.com/${GITHUB_USER}/${REPO_NAME}.git
            
            npm version patch -m "ci: bump version to %s [ci skip]"
            
            git push origin HEAD:main --follow-tags
            
            echo "Version bumped and pushed to GitHub"
          '''
        }
      }
    }
    
    stage('Build Application') {
      steps {
        sh '''
          echo "Building Next.js application..."
          npm run build
          echo "Build completed"
        '''
      }
    }
    
    stage('Docker build') {
      steps {
        sh '''
          IMAGE_TAG="${GITHUB_USER}/${REPO_NAME}:$(git rev-parse --short HEAD)"
          echo "Building Docker image: $IMAGE_TAG"
          docker build -t $IMAGE_TAG .
          echo "Docker image built: $IMAGE_TAG"
        '''
      }
    }
    
    stage('Create and Push Artifact') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: env.GITHUB_CREDENTIALS,
          usernameVariable: 'GIT_USER',
          passwordVariable: 'GIT_TOKEN'
        )]) {
          sh '''
            set -e
            
            BUILD_DATE=$(date +"%Y%m%d-%H%M%S")
            COMMIT_SHA=$(git rev-parse --short HEAD)
            VERSION=$(node -p "require('./package.json').version")
            
            ARTIFACT_NAME="artifact-v${VERSION}-${BUILD_DATE}-${COMMIT_SHA}.tar.gz"
            
            echo "================================================"
            echo "Creating artifact: ${ARTIFACT_NAME}"
            echo "Version: v${VERSION}"
            echo "Date: ${BUILD_DATE}"
            echo "Commit: ${COMMIT_SHA}"
            echo "================================================"
            
            tar -czf ${ARTIFACT_NAME} .next package.json package-lock.json
            
            echo "Artifact created: $(ls -lh ${ARTIFACT_NAME})"
            
            TMPDIR=$(mktemp -d)
            echo "Cloning jenkins-builds repository..."
            git clone https://${GIT_TOKEN}@github.com/${GITHUB_USER}/${BUILD_REPO}.git $TMPDIR
            
            cp ${ARTIFACT_NAME} $TMPDIR/
            
            cd $TMPDIR
            
            git config user.email "jenkins@busra-ertekin.com"
            git config user.name "jenkins-ci"
            
            git add ${ARTIFACT_NAME}
            
            COMMIT_MSG="Add build artifact ${ARTIFACT_NAME}

Project: ${REPO_NAME}
Version: v${VERSION}
Build Date: ${BUILD_DATE}
Commit: ${COMMIT_SHA}
Build Number: ${BUILD_NUMBER}

Generated by Jenkins CI/CD Pipeline"
            
            git commit -m "${COMMIT_MSG}"
            
            echo "Pushing to GitHub..."
            git push origin HEAD:main
            
            cd -
            rm -rf $TMPDIR
            
            echo "================================================"
            echo "SUCCESS! Artifact pushed to GitHub"
            echo "Repository: https://github.com/${GITHUB_USER}/${BUILD_REPO}"
            echo "File: ${ARTIFACT_NAME}"
            echo "================================================"
          '''
        }
      }
    }
    
    stage('Build Summary') {
      steps {
        sh '''
          BUILD_DATE=$(date +"%Y-%m-%d %H:%M:%S")
          COMMIT_SHA=$(git rev-parse --short HEAD)
          VERSION=$(node -p "require('./package.json').version")
          
          echo "========================================"
          echo "BUILD SUMMARY"
          echo "========================================"
          echo ""
          echo "Project:        ${REPO_NAME}"
          echo "Version:        v${VERSION}"
          echo "Build Date:     ${BUILD_DATE}"
          echo "Commit:         ${COMMIT_SHA}"
          echo "Build Number:   ${BUILD_NUMBER}"
          echo ""
          echo "Repositories:"
          echo "  Source:  https://github.com/${GITHUB_USER}/${REPO_NAME}"
          echo "  Builds:  https://github.com/${GITHUB_USER}/${BUILD_REPO}"
          echo ""
          echo "All stages completed successfully!"
          echo ""
        '''
      }
    }
  }
  
  post {
    success {
      echo 'PIPELINE COMPLETED SUCCESSFULLY!'
    }
    failure {
      echo 'PIPELINE FAILED!'
    }
    always {
      cleanWs()
    }
  }
}
